name: Reusable deploy workflow
run-name: ${{ github.ref_name }}
concurrency:
  group: ci-${{ github.workflow }}
  cancel-in-progress: true
on:
  workflow_call:
    inputs:
      build_id:
        required: true
        type: number
      deploy_target:
        required: true
        type: string
      perform_deploy:
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_deploy }}
    steps:
      - name: Deploy build to target
        run: echo "Deploying build:${{ inputs.build_id }} to target:${{ inputs.deploy_target }}"
    
      - uses: actions/cache@v3
        id: cache
        with:
          path: src
          key: ${{ hashFiles('requirements.txt') }}-test
        
      - name: Check if cache was not hit.
        if : steps.cache.outputs.cache-hit != 'true'
        run: echo "Cache was not hit."

      - name: Check if cache was hit.
        if : steps.cache.outputs.cache-hit == 'true'
        run: echo "Cache was found."
